version: 0.2

phases: 
    install:
        commands:
            - echo "Installing dependencies..."
    build:
        commands:
            - echo "Building application..."
            - echo "Checking for the dependency.txt file..."
            - |
                if [ -f "dependency.txt" ]; then
                    echo "File exists, build succeeds."
                else
                    echo "File does not exist, build fails." 
                    exit 1
                fi
    post_build:
        commands:
            - echo "Entered the post_build phase..."
            - echo "Build completed on `date`"
            
            
